package com.automationexercise.qe.ui.tests.smoke;

import com.automationexercise.qe.core.base.BaseTest;
import com.automationexercise.qe.core.config.EnvironmentConfig;
import com.automationexercise.qe.ui.pages.HomePage;
import com.automationexercise.qe.ui.pages.ProductDetailsPage;
import com.automationexercise.qe.ui.pages.ProductsPage;
import com.github.javafaker.Faker;
import io.qameta.allure.Epic;
import io.qameta.allure.Feature;
import io.qameta.allure.Story;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

@Epic("Product Catalog")
@Feature("Product Reviews")
public class ProductReviewTests extends BaseTest {

    private final Faker faker = new Faker();

    @BeforeMethod
    public void setupTest() {
        getDriver().get(EnvironmentConfig.getInstance().getBaseUrl());
    }

    @Test(groups = "regression")
    @Story("Add review on product")
    public void testAddReviewOnProduct() {
        HomePage homePage = new HomePage(getDriver());
        ProductsPage productsPage = homePage.navigateToProducts();
        
        ProductDetailsPage detailsPage = productsPage.viewFirstProductDetails();
        
        detailsPage.submitReview(
                faker.name().firstName(),
                faker.internet().emailAddress(),
                "This is an automated review generated by QE suite!"
        );
        
        Assert.assertTrue(detailsPage.isReviewSuccessful(), "Review success message not displayed");
    }
}
