# QA Environment Specific Configuration
base.url=https://automationexercise.com
api.base.url=https://automationexercise.com/api

# Test Data
qa.test.email=test_qa@testmail.com
qa.test.password=Password123!
